; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = core_flight
name = LUMA

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
build_flags = 
	-std=c++17
	-std=gnu++17
build_unflags = 
	-std=gnu++11
	-std=gnu++14
lib_deps = 
	mbed-usna-wse-es456/BNO055_fusion@0.0.0+sha.ae4be69ac7bb
	adafruit/Adafruit BNO055@^1.6.4
	sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.27
	adafruit/Adafruit BMP3XX Library@^2.1.6
	sv-zanshin/BME280_Zanshin@^1.0.4
build_src_filter = 
	+<*>
	-<**/*_flight.cpp>
	-<**/*_test.cpp>

[env:core_flight]
build_src_filter = 
	${env.build_src_filter}
	+<**/core_flight.cpp>

[env:core_test]
build_src_filter = 
	${env.build_src_filter}
	+<**/core_test.cpp>


[env:lrc_flight]
build_src_filter = 
	${env.build_src_filter}
	+<**/lrc_flight.cpp>


[env:lrc_test]
build_src_filter = 
	${env.build_src_filter}
	+<**/lrc_test.cpp>



[env:vent_drop_flight]
build_src_filter = 
	${env.build_src_filter}
	+<**/vent_drop_flight.cpp>


[env:vent_drop_test]
build_src_filter = 
	${env.build_src_filter}
	+<**/vent_drop_test.cpp>

